apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: app-backend
        image: saksham251/app-backend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: env-file
          readOnly: true
          mountPath: "/APP/secret"
      volumes:
      - name: env-file
        secret:
          secretName: backend-secret
