apiVersion: v1
kind: Secret
metadata: 
  name: backend-secret
data:
  .env: "UE9SVD0zMDAwCkRBVEFCQVNFX1VSTD1wb3N0Z3JzczovL3Bvc3RncmVzOmFkbWluQGxvY2FsaG9zdDo1NDMyClBVQkxJQ19LRVk9R1RDVkdWSEJJVU4KSldUX1NFQ1JFVD1ZRlZHVEJKVUpNT0xLTQ=="
